name: Pipeline with Jest Test (Artifacts)

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Install dependencies
            run: npm install

          - name: Upload build artifact
            uses: actions/upload-artifact@v3
            with:
                name: build-artifact
                path: .next

          - name: Upload dependencies artifact
            uses: actions/upload-artifact@v3
            with:
                name: dependencies-artifact
                path: node_modules
    tests:
        needs: build
        runs-on: ubuntu-22.04
        steps:
          - name: Download build artifacts
            uses: actions/download-artifact@v3
            with:
                name: build-artifact
                path: .next

          - name: Download dependencies artifact
            uses: actions/download-artifact@v3
            with:
                name: dependencies-artifact
                path: node_modules

          - name: Run tests
            run:
                npm test
